#pragma once

// BVEVENTTYPE_{LISTENER}_EVENT
typedef enum class BVEventType
{
    BVEVENTTYPE_DISCOVERY_REQUEST_START,
    BVEVENTTYPE_DISCOVERY_REQUEST_PAUSE,
    BVEVENTTYPE_DISCOVERY_REQUEST_RESUME,
    BVEVENTTYPE_DISCOVERY_REQUEST_SHUTDOWN, // terminate component; usually BVEVENTTYPE_TERMINATE_ALL
    BVEVENTTYPE_DISCOVERY_REQUEST_RESTART, // this shouldn't mean doing anything to the thread
    BVEVENTTYPE_DISCOVERY_REQUEST_RESOLVE,

    BVEVENTTYPE_APP_PUBLISHED_SERVICE, // published service list or pushed on queue
    BVEVENTTYPE_APP_DEREGISTERED_SERVICE,
    BVEVENTTYPE_APP_DISCOVERY_RESUMED,
    BVEVENTTYPE_APP_DISCOVERY_PAUSED,
    BVEVENTTYPE_APP_DISCOVERY_SERVICE_RESOLVED,

    BVEVENTTYPE_SERVICE_REQUEST_START,
    BVEVENTTYPE_SERVICE_REQUEST_SHUTDOWN,

    BVEVENTTYPE_TERMINATE_ALL, // ALL_TERMINATE?

    // Events caused by TCP traffic
    _REDUNDANT_BVEVENTTYPE_APP_SERVICE_DEREGISTERED, // this is handled by mDNS. Probably redundant.
    BVEVENTTYPE_APP_MESSAGE_INCOMING,
    BVEVENTTYPE_APP_FILE_OFFER,            // incoming file offer -> app accepts/rejects
    BVEVENTTYPE_APP_FILE_TRANSFER_BEGIN,
    BVEVENTTYPE_APP_FILE_TRANSFER_CHUNK_SENT,
    BVEVENTTYPE_APP_FILE_TRANSFER_END,
    BVEVENTTYPE_APP_FILE_TRANSFER_CANCELLED,

    // Messages exchanged between Nodes
    // ...

    // Test and Debug events
    BVEVENTTYPE_TEST_ECHO,
    BVEVENTTYPE_TEST_HEARTBEAT,
    BVEVENTTYPE_TEST_HEARTBEAT_ACK,
    BVEVENTTYPE_TEST_HEARTBEAT_NACK,
    BVEVENTTYPE_TEST_REQUEST_START,
    BVEVENTTYPE_TEST_REQUEST_PAUSE,
    BVEVENTTYPE_TEST_REQUEST_RESUME,
    BVEVENTTYPE_TEST_REQUEST_SHUTDOWN,
    BVEVENTTYPE_TEST_REQUEST_RESTART,
    BVEVENTTYPE_TEST_APP_ANNOUNCE_SERVICES, // App announces services
} BVEventType;